version: '3.1'

services:
  db:
    image: postgres:13.1
    privileged: true
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: django
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: db
  backend:
    build:
     context: ./todo
    ports:
      - 8000:8000
    command: bash -c "python3 manage.py migrate && python manage.py create_user && gunicorn todo.wsgi -b 0.0.0.0:8000"
    depends_on:
      - db
  nginx:
    build: ./nginx
    ports:
      - 8000:80
    depends_on:
      - backend
  frontend:
    build: ./frontend
    ports:
      - 80:80
    depends_on:
      - nginx
